/*
 * SPDX-FileCopyrightText: 2023-2026 Laurent Montel <laurent.montel@kdab.com>
 *
 * SPDX-License-Identifier: LGPL-2.0-or-later
 */

import { Page } from "../page.slint";
import { Button, LineEdit, StandardListView } from "std-widgets.slint";
import { PageType } from "../singletons/screencontroller.slint";
import { Icons } from "../icons.slint";

export component MainPage inherits Page {
    screen-id: PageType.MainPage;
    callback send_message(string);
    callback show_accounts();
    callback disconnect_account();
    callback quit();
    preferred-width: 700px;
    preferred-height: 500px;
    // TODO remove default value!
    in-out property <string> room-id: "ff";
    in property <[StandardListViewItem]> room-model;
    in property <[StandardListViewItem]> message-model;
    out property <int> current-room-item: room_list.current-item;
    VerticalLayout {
        HorizontalLayout {
            Button {
                text: @tr("Connect");
                clicked => {
                    root.show_accounts();
                }
            }

            Button {
                text: @tr("Disconnect");
                clicked => {
                    root.disconnect-account();
                }
            }
        }

        HorizontalLayout {
            room_list := StandardListView {
                model: room-model;
            }

            VerticalLayout {
                message_list := StandardListView {
                    enabled: false;
                    model: message-model;
                }

                HorizontalLayout {
                    lineedit := LineEdit {
                        accepted => {
                            if (lineedit.text != "" && room-id != "") {
                                root.send_message(lineedit.text);
                            }
                        }
                    }

                    Button {
                        text: @tr("Send Message");
                        icon: Icons.send-message;
                        clicked => {
                            if (lineedit.text != "" && room-id != "") {
                                root.send_message(lineedit.text);
                            }
                        }
                        enabled: lineedit.text != "" && room-id != "";
                    }
                }
            }
        }
    }
}
