/*
* SPDX-FileCopyrightText: 2025-2026 Laurent Montel <laurent.montel@kdab.com>
*
* SPDX-License-Identifier: LGPL-2.0-or-later
*/
import { Button, StandardButton, AboutSlint} from "std-widgets.slint";

export component AboutDialog inherits Dialog {
    VerticalLayout {
        alignment: center;
        Rectangle {
            AboutSlint {
                width: Math.min(200px, 80% * parent.width);
                min-height: self.preferred-height;
            }
        }
        // TODO add about ruqola rust
    }
}
