/*
* SPDX-FileCopyrightText: 2023-2026 Laurent Montel <laurent.montel@kdab.com>
*
* SPDX-License-Identifier: LGPL-2.0-or-later
*/

import {
    StandardButton,
    Button,
    VerticalBox,
    GridBox,
    StandardListView,
    CheckBox,
} from "std-widgets.slint";
import { Icons } from "../icons.slint";
export component AccountSettingsDialog inherits Dialog {
    title: @tr("Settings");
    callback updatebuttons();
    callback add_new_account_clicked();
    callback remove_account_clicked(int);
    callback modify_account_clicked();
    callback close_clicked();

    in property <[StandardListViewItem]> account-model;
    HorizontalLayout {
        spacing: 12px;
        padding: 10px;

        accountlist := StandardListView {
            model: root.account-model;
            current-item-changed => {
                updatebuttons();
            }
        }

        Rectangle {
            width: 140px;
            background: @linear-gradient(90deg, #f5f5f5, #ffffff);
            VerticalLayout {
                spacing: 6px;
                padding: 8px;
                alignment: start;

                add_button := Button {
                    text: @tr("➕ Add");
                    clicked => {
                        add_new_account_clicked();
                    }
                }

                modify_button := Button {
                    icon: Icons.edit-account;
                    text: @tr("Modify");
                    enabled: false;
                    clicked => {
                        modify_account_clicked();
                    }
                }

                remove_button := Button {
                    text: @tr("🗑 Remove");
                    enabled: false;
                    clicked => {
                        remove_account_clicked(accountlist.current-item);
                    }
                }

                Rectangle {
                    height: 1px;
                }
            }
        }
    }

    updatebuttons => {
        modify_button.enabled = accountlist.current-item != -1;
        remove_button.enabled = accountlist.current-item != -1;
    }

    preferred-height: 400px;
    preferred-width: 600px;
    StandardButton {
        kind: close;
        clicked => {
            close_clicked();
        }
    }
}
